baseURL = 'https://lucasriboli.github.io/'
languageCode = 'en-us'
title = 'OctoRibs'
theme = 'terminal'
defaultContentLanguage = 'en'

# Outras configurações...

[languages]
  [languages.en]
    title = "OctoRibs"
    subtitle = "Your Subtitle"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    
    [languages.en.params.logo]
      logoText = "OctoRibs"
      logoHomeLink = "/"
    
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
  