baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'OctoRibs'
theme = 'terminal'

[params]
  themeColor = "orange"
  themeColorDark = "green"
  showMenuItems = 2
  showLanguageSelector = true
  fullWidthTheme = false
  centerTheme = false
  author = "OctoRibs"

[languages]
  [languages.en]
    languageName = "Português"
    title = "Título do seu site"
    subtitle = "Subtítulo do seu site"
    owner = "OctoRibs"
    keywords = ""
    copyright = ""
    menuMore = "Mostrar mais"
    readMore = "Ler mais"
    readOtherPosts = "Ler outros posts"
    
    [languages.en.params.logo]
      logoText = "OctoRibs"
      logoHomeLink = "/"
    
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "Sobre"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"