baseURL = 'https://lucasriboli.github.io/'
languageCode = 'en-us'
title = 'OctoRibs'
theme = 'terminal'

[params]
  # Cor do tema ("orange", "blue", "red", "green", "pink")
  themeColor = "green"
  
  # Para tema escuro
  # themeColorDark = "green"
  
  # Se você usar favicon
  favicon = "/favicon.ico"
  
  # Imagens em tela cheia
  fullWidthTheme = false
  
  # Centralizar conteúdo
  centerTheme = true
  
  # Menus a mostrar
  showMenuItems = 5
  
  # Mostrar datas de leitura para posts
  showReadingTime = true

[languages]
  [languages.pt]
    title = "OctoRibs"
    subtitle = "Seu Subtítulo"
    keywords = ""
    copyright = ""
    menuMore = "Mostrar mais"
    readMore = "Ler mais"
    readOtherPosts = "Ler outros posts"
    
    [languages.pt.params.logo]
      logoText = "OctoRibs"
      logoHomeLink = "/"
    
    [languages.pt.menu]
      [[languages.pt.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.pt.menu.main]]
        identifier = "about"
        name = "About"
        url = "/About"